apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  labels:
    ui.platform-mesh.io/content-for: kbind.platform-mesh.io
  name: kbind.platform-mesh.io
spec:
  resources:
    - group: kbind.platform-mesh.io
      name: dummies
      schema: today.dummies.kbind.platform-mesh.io
      storage:
        crd: {}
  permissionClaims:
    - group: ""
      resource: namespaces
      verbs: ["create", "get"]
    - group: ""
      resource: serviceaccounts
      verbs: ["create", "get", "delete"]
    - group: ""
      resource: secrets
      verbs: ["create", "get", "delete"]
    - group: "rbac.authorization.k8s.io"
      resource: clusterrolebindings
      verbs: ["create", "get", "delete"]
